_wandb:
    value:
        cli_version: 0.23.1
        code_path: source-Trm_data-ACT-torch-pretrain.py
        e:
            8q6316nd6jd5gehprpqi94b3kmxkwbhv:
                args:
                    - arch=trm
                    - data_paths=[/Users/brunolucena/workspace/bruno/repos/homelab/flux/ai/trm-finetune/models/trm-runbook-only/trm_data]
                    - evaluators=[]
                    - epochs=2
                    - eval_interval=2
                    - lr=0.0001
                    - puzzle_emb_lr=0.0001
                    - weight_decay=1.0
                    - puzzle_emb_weight_decay=1.0
                    - global_batch_size=128
                    - arch.L_layers=2
                    - arch.H_cycles=3
                    - arch.L_cycles=6
                    - arch.pos_encodings=none
                    - +run_name=trm-runbook-test
                    - ema=True
                codePath: pretrain.py
                codePathLocal: pretrain.py
                email: bruno@lucena.cloud
                executable: /Users/brunolucena/workspace/bruno/repos/homelab/flux/ai/trm-finetune/.venv/bin/python
                git:
                    commit: 7de0d20c8f26df706e2c7b3a21ceaf0b3542c953
                    remote: https://github.com/SamsungSAILMontreal/TinyRecursiveModels.git
                host: studio.local
                os: macOS-26.1-arm64-arm-64bit-Mach-O
                program: /Users/brunolucena/workspace/bruno/repos/homelab/flux/ai/trm/../trm/pretrain.py
                python: CPython 3.13.6
                root: /Users/brunolucena/workspace/bruno/repos/homelab/flux/ai/trm
                startedAt: "2025-12-30T17:52:08.846227Z"
                writerId: 8q6316nd6jd5gehprpqi94b3kmxkwbhv
        m: []
        python_version: 3.13.6
        t:
            "1":
                - 1
                - 50
            "2":
                - 1
                - 50
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.13.6
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
arch:
    value:
        H_cycles: 3
        H_layers: 0
        L_cycles: 6
        L_layers: 2
        expansion: 4
        forward_dtype: bfloat16
        halt_exploration_prob: 0.1
        halt_max_steps: 16
        hidden_size: 512
        loss:
            loss_type: stablemax_cross_entropy
            name: losses@ACTLossHead
        mlp_t: false
        name: recursive_reasoning.trm@TinyRecursiveReasoningModel_ACTV1
        no_ACT_continue: true
        num_heads: 8
        pos_encodings: none
        puzzle_emb_len: 16
        puzzle_emb_ndim: 512
beta1:
    value: 0.9
beta2:
    value: 0.95
checkpoint_every_eval:
    value: true
checkpoint_path:
    value: checkpoints/Trm_data-ACT-torch/trm-runbook-test
data_paths:
    value:
        - /Users/brunolucena/workspace/bruno/repos/homelab/flux/ai/trm-finetune/models/trm-runbook-only/trm_data
data_paths_test:
    value: []
ema:
    value: true
ema_rate:
    value: 0.999
epochs:
    value: 2
eval_interval:
    value: 2
eval_save_outputs:
    value: []
evaluators:
    value: []
freeze_weights:
    value: false
global_batch_size:
    value: 128
load_checkpoint:
    value: null
lr:
    value: 0.0001
lr_min_ratio:
    value: 1
lr_warmup_steps:
    value: 2000
min_eval_interval:
    value: 0
project_name:
    value: Trm_data-ACT-torch
puzzle_emb_lr:
    value: 0.0001
puzzle_emb_weight_decay:
    value: 1
run_name:
    value: trm-runbook-test
seed:
    value: 0
weight_decay:
    value: 1
