apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agent-screenshot

resources:
  - namespace.yaml
  - lambdaagent.yaml

commonLabels:
  app.kubernetes.io/name: agent-screenshot
  app.kubernetes.io/part-of: agent-screenshot
