apiVersion: v1
kind: ConfigMap
metadata:
  name: rekordbox-cloud-config
  namespace: rekordbox-cloud
data:
  minio.endpoint: "http://minio.homelab-services.svc.cluster.local:9000"
  minio.bucket: "rekordbox-library"
  analysis.enabled: "true"
  sync.enabled: "true"
