apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rekordbox-cloud

resources:
  - namespace.yaml
  - server.yaml
  - configmap.yaml
  - secret.yaml

commonLabels:
  app: rekordbox-cloud
  managed-by: flux
