---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ollama
  namespace: ollama

resources:
  - namespace.yaml
  - service-native.yaml  # Points to native Ollama on Mac (GPU)

commonLabels:
  app.kubernetes.io/part-of: ollama
  app.kubernetes.io/managed-by: kustomize
