apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: medical-service-platform

resources:
  - namespace.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - secrets-job.yaml

commonLabels:
  app: medical-service
  managed-by: kustomize
