apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: medical-service-role
  namespace: medical-service-platform
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: medical-service-rolebinding
  namespace: medical-service-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: medical-service-role
subjects:
- kind: ServiceAccount
  name: medical-service
  namespace: medical-service-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: medical-service
  namespace: medical-service-platform
