apiVersion: v1
kind: Service
metadata:
  name: medical-service
  namespace: medical-service-platform
  labels:
    app: medical-service
spec:
  selector:
    app: medical-service
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP
