---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: futboss-ai

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - secret.yaml
  - mongodb.yaml
  - redis.yaml
  - deployment.yaml
  - service.yaml
