---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rpg-config
  namespace: ai
  labels:
    app.kubernetes.io/name: rpg-config
    app.kubernetes.io/part-of: agent-rpg
data:
  broker_url: "http://broker-ingress.knative-eventing.svc.cluster.local/agent-rpg/default"
  game_master_url: "http://game-master.agent-rpg.svc.cluster.local"
  ollama_url: "http://ollama-native.ollama.svc.cluster.local:11434"
  default_model: "llama3.2:3b"
