---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-mag7-battle

resources:
  - ../base

patches:
  - patch: |-
      - op: replace
        path: /spec/scaling/minReplicas
        value: 1
    target:
      kind: LambdaFunction
      name: mag7-game-server
