apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agent-store-multibrands

resources:
  - deployment.yaml
  - cloudflare-tunnel-ingress.yaml

commonLabels:
  app.kubernetes.io/component: command-center
  app.kubernetes.io/version: "1.0.0"
