apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: github-runners
  namespace: github-runners

resources:
  - namespace.yaml
  - secrets-job.yaml
  - controller-helmrelease.yaml