apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agent-restaurant

labels:
  - pairs:
      app.kubernetes.io/part-of: agent-restaurant
      app.kubernetes.io/component: web

resources:
  - deployment.yaml
  - rbac.yaml
  - cloudflare-tunnel-ingress.yaml

commonLabels:
  app.kubernetes.io/version: "1.0.0"
