---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai

resources:
  - flux-reconcile-kustomization.yaml
  - pod-restart.yaml
  - pod-check-status.yaml
  - scale-deployment.yaml
  - check-pvc-status.yaml
  - flux-reconcile-gitrepository.yaml
  - flux-reconcile-helmrelease.yaml
  - upload-job.yaml

