---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai

resources:
  - crds.yaml
  - rbac.yaml
  - lambdaagent.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: homelab-ai
    includeSelectors: false
