---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sealed-secrets-alerts
  namespace: prometheus
  labels:
    app: sealed-secrets
    prometheus: kube-prometheus-stack
spec:
  groups:
    - name: sealed-secrets
      interval: 30s
      rules:
        - alert: SealedSecretsControllerAbsent
          annotations:
            description: "sealed-secrets-controller has disappeared from Prometheus target discovery."
            summary: "Sealed Secrets controller is down"
          expr: |
            absent(up{job="sealed-secrets-controller"})
          for: 10m
          labels:
            severity: critical

        - alert: SealedSecretsUnsealErrorsHigh
          annotations:
            description: "Sealed Secrets controller is experiencing high unseal error rate."
            summary: "High unseal error rate"
          expr: |
            rate(sealed_secrets_controller_unseal_errors_total[5m]) > 0.1
          for: 5m
          labels:
            severity: warning

