---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# ğŸŒ Linkerd Multicluster Extension
# Installs and links clusters for multicluster service mesh

resources:
  # 1. Install Linkerd Multicluster Extension
  - ../linkerd/linkerd-multicluster-install-job.yaml
  
  # 2. Link studio cluster to pro and air clusters
  - ../linkerd/linkerd-multicluster-link-job.yaml

