---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# ğŸ Studio Cluster - Extra Infrastructure
# Optional/additional infrastructure components

resources:
  - ../../../../infrastructure/linkerd-multicluster

