---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres-ha

resources:
  - namespace.yaml
  - minio-credentials.yaml
  - cloudnative-pg-operator.yaml
  - homepage-cluster.yaml
  - scheduled-backup.yaml
  - pooler.yaml
  - servicemonitor.yaml
  - alerts.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: homepage
    includeSelectors: false

