apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - nginx-configmap.yaml
  - deployment.yaml
  - service.yaml
  - cloudflare-tunnel-ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false

