---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# ðŸ”„ Studio-1-Node Cluster - CI/CD
# CI/CD components for the studio cluster

resources:
  - ../../../../infrastructure/github-runners
  - ../../../../infrastructure/github-runners/studio

