apiVersion: v1
kind: Service
metadata:
  name: c2-backend
  namespace: knative-lambda-c2
  labels:
    app.kubernetes.io/name: knative-lambda-c2
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: knative-lambda-c2
    app.kubernetes.io/component: backend
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
