apiVersion: v1
kind: Service
metadata:
  name: c2-frontend
  namespace: knative-lambda-c2
  labels:
    app.kubernetes.io/name: knative-lambda-c2
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: knative-lambda-c2
    app.kubernetes.io/component: frontend
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
