---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# ğŸ” Alloy - Grafana telemetry collector
# Collects logs and metrics from pods and nodes

resources:
  - namespace.yaml
  - helmrelease.yaml

