apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden-api
  namespace: vaultwarden
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - vaultwarden.lucena.cloud
    secretName: vaultwarden-api-tls
  rules:
  - host: vaultwarden.lucena.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vaultwarden-api
            port:
              number: 80
