apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai

resources:
- ../base

patches:
- target:
    kind: LambdaAgent
    name: agent-sre
  patch: |-
    - op: replace
      path: /spec/scaling/maxReplicas
      value: 3
    - op: replace
      path: /spec/resources/requests/cpu
      value: "100m"
    - op: replace
      path: /spec/resources/requests/memory
      value: "256Mi"
    - op: replace
      path: /spec/resources/limits/cpu
      value: "500m"
    - op: replace
      path: /spec/resources/limits/memory
      value: "512Mi"

