# ğŸ½ï¸ Agent-Restaurant Namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: ai
  labels:
    app.kubernetes.io/name: agent-restaurant
    app.kubernetes.io/part-of: homelab
    knative.dev/eventing-enabled: "true"
