---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai

resources:
  # Flux Reconciliation Functions
  - flux-reconcile-kustomization.yaml
  - flux-reconcile-gitrepository.yaml
  - flux-reconcile-helmrelease.yaml
  
  # Pod Operations
  - pod-restart.yaml
  - pod-check-status.yaml
  
  # Storage Operations
  - check-pvc-status.yaml
  
  # Scaling Operations
  - scale-deployment.yaml


