apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cloudflare-tunnel-operator
  namespace: cloudflare-tunnel

resources:
  - crd.yaml
  - rbac.yaml
  - deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/name: cloudflare-tunnel-operator
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
