apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ml-platform

resources:
  - ../base

patches:
  - path: patch-configmap.yaml
    target:
      kind: ConfigMap
      name: trm-finetune-config

commonLabels:
  app: trm-finetune
  component: ml-training
  environment: production


