apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac-controller.yaml
  - rbac-webhook.yaml
  - crd.yaml
  - controller-deployment.yaml
  - webhook-configurations.yaml
  - webhook-secret.yaml
  - webhook-deployment.yaml
  - webhook-service.yaml

