# Copyright 2021 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-broker-webhook
  namespace: knative-eventing
  labels:
    rabbitmq.eventing.knative.dev/release: "v1.17.6"
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: rabbitmq-broker-webhook
      role: rabbitmq-broker-webhook
  template:
    metadata:
      labels: *labels
    spec:
      # To avoid node becoming SPOF, spread our replicas to different nodes.
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: rabbitmq-broker-webhook
                topologyKey: kubernetes.io/hostname
              weight: 100
      serviceAccountName: rabbitmq-broker-webhook
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: rabbitmq-broker-webhook
          terminationMessagePolicy: FallbackToLogsOnError
          # This is the Go import path for the binary that is containerized
          # and substituted here.
          image: localhost:5001/knative-rabbitmq-broker-webhook:v1.17.6
          resources:
            # requests:
            #   # taken from serving.
            #   cpu: 100m
            #   memory: 512Mi
            limits:
              # taken from serving.
              # cpu: 500m
              memory: 512Mi
          env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIG_LOGGING_NAME
              value: config-logging
            - name: METRICS_DOMAIN
              value: knative.dev/sources
            - name: WEBHOOK_NAME
              value: rabbitmq-broker-webhook
            - name: WEBHOOK_PORT
              value: "8443"
            - name: WEBHOOK_SECRET_NAME
              value: rabbitmq-broker-webhook-certs
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - all
          ports:
            - name: https-webhook
              containerPort: 8443
            - name: metrics
              containerPort: 9090
            - name: profiling
              containerPort: 8008
          readinessProbe: &probe
            periodSeconds: 1
            httpGet:
              scheme: HTTPS
              port: 8443
              httpHeaders:
                - name: k-kubelet-probe
                  value: "webhook"
          livenessProbe:
            !!merge <<: *probe
            initialDelaySeconds: 20
      # nodeSelector:
      #   knative: "true"
      # tolerations:
      #   - key: knative
      #     operator: Equal
      #     value: "true"
      #     effect: NoSchedule
      # Our webhook should gracefully terminate by lame ducking first, set this to a sufficiently
      terminationGracePeriodSeconds: 300

