---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai

resources:
  - ../base

patches:
  - patch: |-
      - op: replace
        path: /spec/image/repository
        value: ghcr.io/brunolucena/agent-blueteam/defense-runner
      - op: replace
        path: /spec/scaling/minReplicas
        value: 1
      - op: replace
        path: /spec/scaling/maxReplicas
        value: 5
    target:
      kind: LambdaAgent
      name: agent-blueteam
