apiVersion: v1
kind: Secret
metadata:
  name: dj-collab-p2p-secrets
  namespace: dj-collab-p2p
type: Opaque
stringData:
  mongodb-uri: "mongodb://mongodb.dj-collab-p2p.svc.cluster.local:27017"
  redis-uri: "redis://redis.dj-collab-p2p.svc.cluster.local:6379"
