apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spotify-p2p

resources:
  - namespace.yaml
  - server.yaml
  - configmap.yaml
  - secret.yaml

commonLabels:
  app: spotify-p2p
  managed-by: flux
