apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agent-pos-edge

labels:
  - pairs:
      app.kubernetes.io/part-of: agent-pos-edge
      app.kubernetes.io/component: web-mcdonalds

resources:
  - deployment.yaml
  - cloudflare-tunnel-ingress.yaml

commonLabels:
  app.kubernetes.io/version: "1.0.0"
